version: '3.0'

services:
  django_api:
    build: .
    image: chrisemke/junglechallenge:0.1
    container_name: django
    volumes:
      - django_api:/code
    ports:
      - 8000:8000
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: challenge
      POSTGRES_DB: challenge
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  django_api:
