# Generated by Django 3.1.5 on 2021-08-07 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='image',
            new_name='picture',
        ),
    ]
